//
//  LoginModels.swift
//  ios-mobile-master
//
//  Created by Josaphat Campos Pereira on 29/02/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            var userModel: UserModel
        }
        struct Response
        {
            var userModel: UserModel
        }
        struct ViewModel
        {
            var userModel: UserModel
        }
        
        struct ViewError
        {
            var error: Error
        }
    }
}
