//
//  LoginPresenter.swift
//  ios-mobile-master
//
//  Created by Josaphat Campos Pereira on 29/02/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentSomething(response: Login.Something.Response)
    func presentError(error: Login.Something.ViewError)
}

class LoginPresenter: LoginPresentationLogic
{
    
    
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Login.Something.Response)
    {
        let viewModel = Login.Something.ViewModel(userModel: UserModel(email: response.userModel.email, password: response.userModel.password))        
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentError(error: Login.Something.ViewError) {
        viewController?.displayError(error: error)
    }
    
    
}
